#!/bin/bash

# Lighthouse Performance Audit Script
# YYC³ AI Intelligence Platform

set -e

echo "🚀 Starting Lighthouse Performance Audit..."
echo ""

# Configuration
PORT=${1:-3200}
BASE_URL="http://localhost:$PORT"
OUTPUT_DIR="./lighthouse-results"
TIMESTAMP=$(date +"%Y%m%d_%H%M%S")

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Check if server is running
if ! curl -s "$BASE_URL" > /dev/null 2>&1; then
    echo "❌ Server not running at $BASE_URL"
    echo "Please start the dev server first: pnpm dev"
    exit 1
fi

echo "✅ Server detected at $BASE_URL"
echo ""

# Pages to audit
PAGES=(
    "/"
    "/dashboard"
    "/explorer"
    "/trends"
    "/creative"
)

echo "📊 Auditing ${#PAGES[@]} pages..."
echo ""

# Run Lighthouse for each page
for PAGE in "${PAGES[@]}"; do
    URL="${BASE_URL}${PAGE}"
    SAFE_NAME=$(echo "$PAGE" | sed 's/\//_/g' | sed 's/^_//')
    
    echo "🔍 Auditing: $URL"
    
    lighthouse "$URL" \
        --output html \
        --output json \
        --output-path "${OUTPUT_DIR}/report_${SAFE_NAME}_${TIMESTAMP}" \
        --chrome-flags="--headless --no-sandbox --disable-gpu" \
        --quiet \
        || echo "⚠️ Warning: Failed to audit $URL"
    
    echo "   ✅ Report saved: report_${SAFE_NAME}_${TIMESTAMP}.html/json"
done

echo ""
echo "📈 Generating Summary..."
echo ""

# Generate summary
cat > "${OUTPUT_DIR}/summary_${TIMESTAMP}.md" << EOF
# Lighthouse Performance Audit Report

**Generated:** $(date)
**Platform:** YYC³ AI Intelligence Platform
**Environment:** Development (port $PORT)

## 🎯 Core Web Vitals Targets

| Metric | Target | Good | Needs Improvement |
|--------|--------|------|-------------------|
| **LCP** | ≤2.5s | ≤2.5s | >4.0s |
| **FID/TBT** | ≤200ms | ≤200ms | >300ms |
| **CLS** | ≤0.1 | ≤0.1 | >0.25 |

## 📊 Category Scores Target

| Category | Minimum | Target |
|----------|---------|--------|
| Performance | ≥90 | ≥95 |
| Accessibility | ≥92 | ≥98 |
| Best Practices | ≥90 | ≥95 |
| SEO | ≥90 | ≥95 |

## 🔍 Audited Pages

EOF

# Add results for each page
for PAGE in "${PAGES[@]}"; do
    SAFE_NAME=$(echo "$PAGE" | sed 's/\//_/g' | sed 's/^_//')
    REPORT_FILE="${OUTPUT_DIR}/report_${SAFE_NAME}_${TIMESTAMP}.json"
    
    if [ -f "$REPORT_FILE" ]; then
        PERFORMANCE=$(jq '.categories.performance.score * 100' "$REPORT_FILE")
        ACCESSIBILITY=$(jq '.categories.accessibility.score * 100' "$REPORT_FILE")
        BEST_PRACTICES=$(jq '.categories["best-practices"].score * 100' "$REPORT_FILE")
        SEO=$(jq '.categories.seo.score * 100' "$REPORT_FILE")
        
        cat >> "${OUTPUT_DIR}/summary_${TIMESTAMP}.md" << EOF
### ${PAGE:-/}

- **Performance:** ${PERFORMANCE%.*}/100
- **Accessibility:** ${ACCESSIBILITY%.*}/100
- **Best Practices:** ${BEST_PRACTICES%.*}/100
- **SEO:** ${SEO%.*}/100

EOF
    fi
done

cat >> "${OUTPUT_DIR}/summary_${TIMESTAMP}.md" << EOF
---

## 💡 Recommendations

### Performance Optimization
1. **Bundle Size**: Keep JavaScript bundles under 500KB compressed
2. **Lazy Loading**: Implement code splitting for routes
3. **Image Optimization**: Use WebP/AVIF format, lazy load images
4. **Caching**: Configure proper cache headers for static assets

### Accessibility Improvements
1. Ensure all interactive elements have ARIA labels
2. Verify keyboard navigation works correctly
3. Add alt text to all images
4. Maintain sufficient color contrast ratios

### Best Practices
1. Use HTTPS for all resources
2. Remove console.log statements from production
3. Implement proper error boundaries
4. Set up CSP headers

## 📁 Reports Location

All reports saved to: \`$OUTPUT_DIR\`

To view HTML reports:
\`\`\`bash
open ${OUTPUT_DIR}/*.html
\`\`\`

---
*Generated by Lighthouse CI Script v1.0*
EOF

echo "✅ Summary generated: summary_${TIMESTAMP}.md"
echo ""

# Display quick results
echo "=== Quick Results ==="
for PAGE in "${PAGES[@]}"; do
    SAFE_NAME=$(echo "$PAGE" | sed 's/\//_/g' | sed 's/^_//')
    REPORT_FILE="${OUTPUT_DIR}/report_${SAFE_NAME}_${TIMESTAMP}.json"
    
    if [ -f "$REPORT_FILE" ]; then
        SCORE=$(jq '.categories.performance.score * 100' "$REPORT_FILE")
        STATUS="✅"
        if (( $(echo "$SCORE < 90" | bc -l) )); then
            STATUS="❌"
        elif (( $(echo "$SCORE < 95" | bc -l) )); then
            STATUS="⚠️"
        fi
        
        echo "$STATUS $PAGE: Performance ${SCORE%.*}/100"
    fi
done

echo ""
echo "🎉 Audit Complete!"
echo "📁 Results: $OUTPUT_DIR"
echo "📄 Summary: ${OUTPUT_DIR}/summary_${TIMESTAMP}.md"
